{"quit", {
	""}, 0},  // quit and exit function already handled
{"exit", {
	""}, 0},
{"calculate", {
	""}, CommandHandler::Calculate},
{"analyize", {
	""}, CommandHandler::Calculate},
{"help", {
	"*",  // match anything
	""}, CommandHandler::help_handler},
{"set", {
	"on",
	"off",
	"topology_calculations",
	"interface_calculations",
	"metric_calculations",
	"algebraic_calculations",
	"diagnostic_calculations",
	"traditional_calculations",
	"verbose_model",
	"individual_output",
	"quads_share_three_nodes",
	"all",
	"none",
	"exterior",
	"autofit",
	"point size",
	"quick transform",
	"" }, CommandHandler::Set},
{"set hex", {
	"minimum",
	"maximum",
	"aspect",
	"skew",
	"taper",
	"volume",
	"stretch",
	"diagonal",
	"dimension",
	"oddy",
	"condition",
	"jacobian",
	"scaled jacobian",
	"shear",
	"shape",
	"relative size",
	"shape and size",
	""}, CommandHandler::SetHex},
{"set tet", {
	"minimum",
	"maximum",
	"aspect",
	"aspect gamma",
	"volume",
	"condition",
	"jacobian",
	"scaled jacobian",
	"shear",
	"shape",
	"relative size",
	"shape and size",
	""}, CommandHandler::SetTet},
{"set pyramid" , {
	"volume",
	"maximum",
	"minimum",
	"" }, CommandHandler::SetPyramid},
{"set wedge", {
	"volume",
	"minimum",
	"maximum",
	"" }, CommandHandler::SetWedge},
{"set quad", {
	"minimum",
	"maximum",
	"aspect",
	"skew",
	"taper",
	"warpage",
	"area",
	"stretch",
	"smallest angle",
	"largest angle",
	"oddy",
	"condition",
	"jacobian",
	"scaled jacobian",
	"shear",
	"shape",
	"relative size",
	"shape and size",
	"" } , CommandHandler::SetQuad},
{"set tri", {
	"minimum",
	"maximum",
	"aspect",
	"area",
	"smallest angle",
	"largest angle",
	"condition",
	"scaled jacobian",
	"shear",
	"shape",
	"relative size",
	"shape and size",
	"" }, CommandHandler::SetTri},
{"set edge", {
	"minimum",
	"maximum",
	"length",
	"" }, CommandHandler::SetEdge},
{"set knife", {
	"minimum",
	"maximum",
	"volume",
	"" }, CommandHandler::SetKnife},
{"open", {
	"block_info",
	"blocks",
	"add",
	"" }, CommandHandler::open_mesh},
{"playback", {
        "" }, CommandHandler::PlayJournal},
{"record", {
	"stop",
	"", }, CommandHandler::record_handler },
{"echo", {
	"on",
	"off",
	"" }, CommandHandler::echo_handler },
{"load defaults", {
	"" }, CommandHandler::load_defaults },
{"block", {
    "on",
    "off",
    "" }, CommandHandler::toggle_blocks },
{"nodeset", {
    "on",
    "off",
    "" }, CommandHandler::toggle_node_bcs },

{"sideset", {
    "on",
    "off",
    "" }, CommandHandler::toggle_element_bcs },
{"save", {
    "exodus",
    "genesis",
    "" }, CommandHandler::save_mesh },

// commands for the GUI version
{"graphics", {
	"mode",
	"smoothshade",
	"wireframe",
	"hiddenline",
        "reset",
        "perspective",
        "on",
        "off",
	"" }, CommandHandler::graphics_handler },
{"highlight", {
	"failed",
	"hexes",
	"tets",
	"quads",
	"tris",
        "edges",
        "nodes",
	"metric",
	"aspect",
	"area",
	"aspect gamma",
	"skew",
	"taper",
	"volume",
	"stretch",
	"diagonal",
	"dimension",
	"oddy",
	"condition",
	"jacobian",
	"scaled jacobian",
	"shear",
	"shape",
	"relative size",
	"shape and size",
	"warpage",
	"largest angle",
	"smallest angle",
        "share three nodes",
        "coincident",
        "nonconformal",
        "nonmanifold",
        "length",
	"" }, CommandHandler::graphics_highlight_handler },

{"display", {
	"" }, CommandHandler::graphics_display_handler },
{"normals", {
	"on",
	"off",
	"" }, CommandHandler::draw_normals }, 
{"skin", {
	"on",
	"off",
	"" }, CommandHandler::draw_skin }, 
{"model edges", {
	"on",
	"off",
	"" }, CommandHandler::draw_model_edges }, 
{"label", {
	"nodes",
	"elements",
	"failed",
	"nodesets",
	"sidesets",
	"blocks",
	"on",
	"off",
	"" }, CommandHandler::label }, 
{"draw", {
	"hex",
	"tet",
	"quad",
	"tri",
	"edge",
	"node",
	"knife",
	"wedge",
	"pyramid",
	"to",
	"" }, CommandHandler::draw_handler },
