

"set topology_calculations",
"set interface_calculations",
"set metric_calculations",

// file output is not an option
"# file output option has been removed",

"set verbose_model",
"set individual_output",

// warning level was removed
"# warning level has been removed, check the quads_share_three_nodes feature",

"set hex aspect minimum",
"set hex aspect maximum",
"set hex skew minimum",
"set hex skew maximum",
"set hex taper minimum",
"set hex taper maximum",
"set hex volume minimum",
"set hex volume maximum",
"set hex stretch minimum",
"set hex stretch maximum",
"set hex diagonal minimum",
"set hex diagonal maximum",
"set hex dimension minimum",
"set hex dimension maximum",
"set hex oddy minimum",
"set hex oddy maximum",
"set hex condition minimum",
"set hex condition maximum",
"set hex jacobian minimum",
"set hex jacobian maximum",
"set hex scaled jacobian minimum",
"set hex scaled jacobian maximum",
"set hex shear minimum",
"set hex shear maximum",
"set hex shape minimum",
"set hex shape maximum",
"set hex relative size minimum",
"set hex relative size maximum",
"set hex shape and size minimum",
"set hex shape and size maximum",


"set tet aspect minimum",
"set tet aspect maximum",
"set tet aspect gamma minimum",
"set tet aspect gamma maximum",
"set tet volume minimum",
"set tet volume maximum",
"set tet condition minimum",
"set tet condition maximum",
"set tet jacobian minimum",
"set tet jacobian maximum",
"set tet scaled jacobian minimum",
"set tet scaled jacobian maximum",
"set tet shear minimum",
"set tet shear maximum",
"set tet shape minimum",
"set tet shape maximum",
"set tet relative size minimum",
"set tet relative size maximum",
"set tet shape and size minimum",
"set tet shape and size maximum",


"set pyramid volume minimum",
"set pyramid volume maximum",


"set wedge volume minimum",
"set wedge volume maximum",


"set knife volume minimum",
"set knife volume maximum",


"set quad aspect minimum",
"set quad aspect maximum",
"set quad skew minimum",
"set quad skew maximum",
"set quad taper minimum",
"set quad taper maximum",
"set quad warpage minimum",
"set quad warpage maximum",
"set quad area minimum",
"set quad area maximum",
"set quad stretch minimum",
"set quad stretch maximum",
"set quad largest angle minimum",
"set quad largest angle maximum",
"set quad smallest angle minimum",
"set quad smallest angle maximum",
"set quad oddy minimum",
"set quad oddy maximum",
"set quad condition minimum",
"set quad condition maximum",
"set quad jacobian minimum",
"set quad jacobian maximum",
"set quad scaled jacobian minimum",
"set quad scaled jacobian maximum",
"set quad shear minimum",
"set quad shear maximum",
"set quad shape minimum",
"set quad shape maximum",
"set quad relative size minimum",
"set quad relative size maximum",
"set quad shape and size minimum",
"set quad shape and size maximum",



"set tri aspect minimum",
"set tri aspect maximum",
"set tri area minimum",
"set tri area maximum",
"set tri largest angle minimum",
"set tri largest angle maximum",
"set tri smallest angle minimum",
"set tri smallest angle maximum",
"set tri condition minimum",
"set tri condition maximum",
"set tri scaled jacobian minimum",
"set tri scaled jacobian maximum",
"set tri shear minimum",
"set tri shear maximum",
"set tri shape minimum",
"set tri shape maximum",
"set tri relative size minimum",
"set tri relative size maximum",
"set tri shape and size minimum",
"set tri shape and size maximum",


"set edge length minimum",
"set edge length maximum",

